// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://phswzaksfsonzojrzyag.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBoc3d6YWtzZnNvbnpvanJ6eWFnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzA2NzU2MTIsImV4cCI6MjA4NjI1MTYxMn0.RNAmoI4Eqh9wiHaB3ZdUBfO-rIybtRM5YdS55ovX7ic";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
